[Overlay]
# Position on screen
x = 0
y = 0
# Dimensions
width = 180
height = 180
# Opacity from 0.1 to 0.95
opacity = 0.6
exit_hotkey = ctrl+alt+shift+f7

[Map aliases]
# I find the file names are not the names DBD presents on the loading screen.
# Fix these with aliases here.
lerys = treatment theater
decimated borgo = the decimated borgo
ormond = mount ormond resort
temple of purgation = the temple of purgation
preschool i = badham preschool i
wreckers = wreckers' yard
rpd = raccoon city police station
rpd west wing = raccoon city police station west wing
rpd east wing = raccoon city police station east wing
midwich = midwich elementary school

[Realm aliases]
# As for realm aliases, I only noticed Glenvale has 1 "n".
grave of glennvale = grave of glenvale
badham = springwood